### ISSUE TITLE
Problem with gbk using convertGenbank2table.py

### ISSUE THREAD

**Issue by FelipeMelis** [mattb112885/clusterDbAnalysis#74]
When i use the convertGenbank2table.py with some gbk files, don't generate a tabulated file in the raw folder (is generate a empty txt file) but the script is working with other gbk files downloaded from the same source.

**Comment by mattb112885** [comment]
Felipe,

Do you get any error messages or text printed when trying to create the text file? Have you tried updating your install of Biopython? (NCBI periodically changes their formats and Biopython has to update to parse them correctly)

Otherwise ... if you can link to the genbank file (or send it to mnb_0000 (at) Hotmail (dot) com if you are concerned with data confidentiality ), I will try to figure out why it's happening. I will be out of the country for the next week but can poke around with it when I get back and see if I can figure out what is going on...

Matt

**Comment by FelipeMelis** [comment]
Matt,

I am using the ITEP VM.
I send you a email with the genbank files.

Thanks

**Comment by mattb112885** [comment]
This is resolved (The file was not annotated).
